'use client';
// Boneyard registry — placeholder.
// This file is regenerated by `npx boneyard-js build`. Until then, every
// <Skeleton> renders its `fallback` (or nothing) instead of pixel-perfect bones.
//
// To populate this file, start the dev server and run:
//   npm run bones
import { configureBoneyard, registerBones } from 'boneyard-js/react';

configureBoneyard({
  animate: 'shimmer',
  color: '#e2e8f0',
  darkColor: '#1e293b',
  shimmerColor: '#f1f5f9',
  darkShimmerColor: '#334155',
  speed: '1.8s',
  shimmerAngle: 110,
  stagger: 60,
  transition: 240,
});

registerBones({
  // Populated by `npx boneyard-js build`. Each key is a Skeleton `name`
  // mapped to a per-breakpoint bone array.
});
